Лабораторная работа 2
Очистка данных и подготовка признаков для моделирования  

Цель:
Научиться готовить данные для алгоритмов машинного обучения

Предметная область:
Анализ авиаперевозок и факторов, влияющих на задержки рейсов

Исходные данные:
Датасет из лабораторной работы 1

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import LabelEncoder, StandardScaler

df = pd.read_csv("Airline_Delay_Cause.csv")

df.head()

,year,month,carrier,carrier_name,airport,airport_name,arr_flights,arr_del15,carrier_ct,weather_ct,...,security_ct,late_aircraft_ct,arr_cancelled,arr_diverted,arr_delay,carrier_delay,weather_delay,nas_delay,security_delay,late_aircraft_delay
0,2022,7,9E,Endeavor Air Inc.,ABE,"Allentown/Bethlehem/Easton, PA: Lehigh Valley ...",33.0,2.0,0.92,1.00,...,0.0,0.00,0.0,0.0,129.0,98.0,23.0,8.0,0.0,0.0
1,2022,7,9E,Endeavor Air Inc.,ABY,"Albany, GA: Southwest Georgia Regional",78.0,25.0,11.80,0.72,...,0.0,7.48,0.0,0.0,1664.0,887.0,52.0,224.0,0.0,501.0
2,2022,7,9E,Endeavor Air Inc.,ACK,"Nantucket, MA: Nantucket Memorial",124.0,19.0,5.84,1.00,...,0.0,5.40,5.0,4.0,1523.0,388.0,35.0,511.0,0.0,589.0
3,2022,7,9E,Endeavor Air Inc.,AEX,"Alexandria, LA: Alexandria International",67.0,10.0,1.32,1.00,...,1.0,4.28,0.0,1.0,657.0,103.0,82.0,93.0,25.0,354.0
4,2022,7,9E,Endeavor Air Inc.,AGS,"Augusta, GA: Augusta Regional at Bush Field",174.0,30.0,18.10,5.75,...,0.0,2.55,1.0,0.0,2462.0,1686.0,310.0,139.0,0.0,327.0

In [2]:
df = df.fillna(0)
Q1 = df['arr_delay'].quantile(0.25)
Q3 = df['arr_delay'].quantile(0.75)
IQR = Q3 - Q1
df = df[(df['arr_delay'] >= Q1 - 1.5*IQR) & (df['arr_delay'] <= Q3 + 1.5*IQR)]

Исправлены замечания:
обработаны пропуски  
удалены выбросы

In [3]:
categorical_cols = ['carrier', 'airport']
df[categorical_cols].head()

  carrier airport
0      9E     ABE
1      9E     ABY
2      9E     ACK
3      9E     AEX
4      9E     AGS

Категориальные признаки включают:
авиакомпанию
аэропорт

In [4]:
le = LabelEncoder()
df_le = df.copy()
df_le['carrier'] = le.fit_transform(df_le['carrier'])
df_le['airport'] = le.fit_transform(df_le['airport'])

In [5]:
df_ohe = pd.get_dummies(df, columns=['carrier', 'airport'], drop_first=True)
df_ohe.head()

,year,month,carrier_name,airport_name,arr_flights,arr_del15,carrier_ct,weather_ct,nas_ct,security_ct,...,airport_VLD,airport_VPS,airport_WRG,airport_WYS,airport_XNA,airport_XWA,airport_YAK,airport_YKM,airport_YNG,airport_YUM
0,2022,7,Endeavor Air Inc.,"Allentown/Bethlehem/Easton, PA: Lehigh Valley ...",33.0,2.0,0.92,1.00,0.08,0.0,...,False,False,False,False,False,False,False,False,False,False
1,2022,7,Endeavor Air Inc.,"Albany, GA: Southwest Georgia Regional",78.0,25.0,11.80,0.72,5.01,0.0,...,False,False,False,False,False,False,False,False,False,False
2,2022,7,Endeavor Air Inc.,"Nantucket, MA: Nantucket Memorial",124.0,19.0,5.84,1.00,6.76,0.0,...,False,False,False,False,False,False,False,False,False,False
3,2022,7,Endeavor Air Inc.,"Alexandria, LA: Alexandria International",67.0,10.0,1.32,1.00,2.40,1.0,...,False,False,False,False,False,False,False,False,False,False
4,2022,7,Endeavor Air Inc.,"Augusta, GA: Augusta Regional at Bush Field",174.0,30.0,18.10,5.75,3.60,0.0,...,False,False,False,False,False,False,False,False,False,False

Использованы два метода кодирования:
Label Encoding
One-Hot Encoding

In [6]:
num_cols = ['arr_flights', 'arr_delay', 'carrier_delay', 'weather_delay']
scaler = StandardScaler()
df_scaled = df.copy()
df_scaled[num_cols] = scaler.fit_transform(df_scaled[num_cols])
df_scaled.head()

,year,month,carrier,carrier_name,airport,airport_name,arr_flights,arr_del15,carrier_ct,weather_ct,...,security_ct,late_aircraft_ct,arr_cancelled,arr_diverted,arr_delay,carrier_delay,weather_delay,nas_delay,security_delay,late_aircraft_delay
0,2022,7,9E,Endeavor Air Inc.,ABE,"Allentown/Bethlehem/Easton, PA: Lehigh Valley ...",-0.543838,2.0,0.92,1.00,...,0.0,0.00,0.0,0.0,-0.793999,-0.630188,-0.292853,8.0,0.0,0.0
1,2022,7,9E,Endeavor Air Inc.,ABY,"Albany, GA: Southwest Georgia Regional",-0.280549,25.0,11.80,0.72,...,0.0,7.48,0.0,0.0,0.392316,0.750479,-0.141637,224.0,0.0,501.0
2,2022,7,9E,Endeavor Air Inc.,ACK,"Nantucket, MA: Nantucket Memorial",-0.011410,19.0,5.84,1.00,...,0.0,5.40,5.0,4.0,0.283345,-0.122719,-0.230281,511.0,0.0,589.0
3,2022,7,9E,Endeavor Air Inc.,AEX,"Alexandria, LA: Alexandria International",-0.344909,10.0,1.32,1.00,...,1.0,4.28,0.0,1.0,-0.385938,-0.621439,0.014793,93.0,25.0,354.0
4,2022,7,9E,Endeavor Air Inc.,AGS,"Augusta, GA: Augusta Regional at Bush Field",0.281133,30.0,18.10,5.75,...,0.0,2.55,1.0,0.0,1.009045,2.148645,1.203665,139.0,0.0,327.0

In [8]:
from sklearn.preprocessing import MinMaxScaler
minmax = MinMaxScaler()
df_minmax = df.copy()
df_minmax[num_cols] = minmax.fit_transform(df_minmax[num_cols])
df_minmax.head()

,year,month,carrier,carrier_name,airport,airport_name,arr_flights,arr_del15,carrier_ct,weather_ct,...,security_ct,late_aircraft_ct,arr_cancelled,arr_diverted,arr_delay,carrier_delay,weather_delay,nas_delay,security_delay,late_aircraft_delay
0,2022,7,9E,Endeavor Air Inc.,ABE,"Allentown/Bethlehem/Easton, PA: Lehigh Valley ...",0.006201,2.0,0.92,1.00,...,0.0,0.00,0.0,0.0,0.021909,0.018498,0.005130,8.0,0.0,0.0
1,2022,7,9E,Endeavor Air Inc.,ABY,"Albany, GA: Southwest Georgia Regional",0.014656,25.0,11.80,0.72,...,0.0,7.48,0.0,0.0,0.282609,0.167422,0.011599,224.0,0.0,501.0
2,2022,7,9E,Endeavor Air Inc.,ACK,"Nantucket, MA: Nantucket Memorial",0.023300,19.0,5.84,1.00,...,0.0,5.40,5.0,4.0,0.258662,0.073235,0.007807,511.0,0.0,589.0
3,2022,7,9E,Endeavor Air Inc.,AEX,"Alexandria, LA: Alexandria International",0.012589,10.0,1.32,1.00,...,1.0,4.28,0.0,1.0,0.111583,0.019441,0.018291,93.0,25.0,354.0
4,2022,7,9E,Endeavor Air Inc.,AGS,"Augusta, GA: Augusta Regional at Bush Field",0.032694,30.0,18.10,5.75,...,0.0,2.55,1.0,0.0,0.418139,0.318233,0.069150,139.0,0.0,327.0

Сравнение методов масштабирования:
StandardScaler - нормализация к среднему
MinMaxScaler - приведение к диапазону

In [9]:
df['delay_per_flight'] = df['arr_delay'] / (df['arr_flights'] + 1)
df['total_delay'] = (
    df['carrier_delay'] +
    df['weather_delay'] +
    df['nas_delay'] +
    df['late_aircraft_delay']
)

Созданы новые признаки:
задержка на один рейс
суммарные задержки по причинам

In [10]:
df = df.drop(columns=[
    'carrier_name',
    'airport_name'
])

Удалены признаки:
carrier_name
airport_name
Причина - текстовые дубли категориальных признаков, не несут дополнительной информации

In [11]:
final_df = df.copy()
final_df.head()

,year,month,carrier,airport,arr_flights,arr_del15,carrier_ct,weather_ct,nas_ct,security_ct,...,arr_cancelled,arr_diverted,arr_delay,carrier_delay,weather_delay,nas_delay,security_delay,late_aircraft_delay,delay_per_flight,total_delay
0,2022,7,9E,ABE,33.0,2.0,0.92,1.00,0.08,0.0,...,0.0,0.0,129.0,98.0,23.0,8.0,0.0,0.0,3.794118,129.0
1,2022,7,9E,ABY,78.0,25.0,11.80,0.72,5.01,0.0,...,0.0,0.0,1664.0,887.0,52.0,224.0,0.0,501.0,21.063291,1664.0
2,2022,7,9E,ACK,124.0,19.0,5.84,1.00,6.76,0.0,...,5.0,4.0,1523.0,388.0,35.0,511.0,0.0,589.0,12.184000,1523.0
3,2022,7,9E,AEX,67.0,10.0,1.32,1.00,2.40,1.0,...,0.0,1.0,657.0,103.0,82.0,93.0,25.0,354.0,9.661765,632.0
4,2022,7,9E,AGS,174.0,30.0,18.10,5.75,3.60,0.0,...,1.0,0.0,2462.0,1686.0,310.0,139.0,0.0,327.0,14.068571,2462.0

Финальный датасет подготовлен для построения моделей машинного обучения

Вывод:
Проведена очистка данных и удаление выбросов
Категориальные признаки закодированы двумя методами
Выполнено масштабирование числовых признаков
Созданы новые признаки для улучшения модели
Удалены нерелевантные столбцы

In [21]:
final_df.to_csv("finish.csv", index=False)